- name: Check /opt/python directory
  raw: test -d /opt/python
  register: python_dir_exist
  ignore_errors: True
  changed_when: false 

- name: Create /opt/python directory
  raw: mkdir -p /opt/python 
  when: python_dir_exist is failed

- name: Check if bootstrap is needed
  raw: stat /opt/python/.bootstrapped
  register: need_bootstrap
  ignore_errors: True
  changed_when: "need_bootstrap.rc != 0"

- name: Run bootstrap.sh
  script: bootstrap.sh
  when: need_bootstrap is failed

- name: Check if we need to install pip
  shell: "{{ansible_python_interpreter}} -m pip --version"
  register: need_pip
  ignore_errors: True
  changed_when: false
  when: need_bootstrap is failed

- name: Copy get-pip.py
  copy: src=get-pip.py dest=/opt/python/get-pip.py
  when: need_pip is failed

- name: Install pip
  shell: "{{ansible_python_interpreter}} /opt/python/get-pip.py"
  when: need_pip is failed

- name: Remove get-pip.py
  file: path=/opt/python/get-pip.py state=absent
  when: need_pip is failed

- name: Install pip launcher
  copy: src=runner dest=/opt/python/bin/pip mode=0755
  when: need_pip is failed

- name: Check if we need to install docker-py
  shell: "{{ansible_python_interpreter}} -c 'import docker'"
  register: need_docker_module
  ignore_errors: True
  changed_when: false

- name: Install docker-py
  shell: "{{ansible_python_interpreter}} -m pip install docker"
  when: need_docker_module is failed

- name: Check if we need to install boto
  shell: "{{ansible_python_interpreter}} -c 'import boto'"
  register: need_boto_module
  ignore_errors: True
  changed_when: false

- name: Install boto
  shell: "{{ansible_python_interpreter}} -m pip install boto"
  when: need_boto_module is failed

- name: Check if we need to install boto3
  shell: "{{ansible_python_interpreter}} -c 'import boto3'"
  register: need_boto3_module
  ignore_errors: True
  changed_when: false

- name: Install boto3
  shell: "{{ansible_python_interpreter}} -m pip install boto3"
  when: need_boto3_module is failed

- name: Check if we need to install botocore
  shell: "{{ansible_python_interpreter}} -c 'import botocore'"
  register: need_botocore_module
  ignore_errors: True
  changed_when: false

- name: Install botocore
  shell: "{{ansible_python_interpreter}} -m pip install botocore"
  when: need_botocore_module is failed
